drupal_asg_alarms: 
-   metric: CPUUtilization
    comparison_operator: GreaterThanThreshold
    name: DrupalHighCPU
    description: Scale-up if CPU > 90% for 10 minutes
    threshold: 90
    policy: DrupalScaleUpPolicy
-   metric: CPUUtilization
    comparison_operator: LessThanThreshold
    name: DrupalLowCPU
    description: Scale-down if CPU <70% for 10 minutes
    threshold: 70
    policy: DrupalScaleDownPolicy
drupal_asg_grace_period: 23
drupal_content_files: 
-   path: sites/all/themes
    url: https://s3.amazonaws.com/s3-helix-ama/themes.tar.gz
-   path: sites/all/modules
    url: https://s3.amazonaws.com/s3-helix-ama/modules.tar.gz
-   path: sites/all/deploy
    url: https://s3.amazonaws.com/s3-helix-ama/deploy.tar.gz
-   metric: CPUUtilization
    comparison_operator: LessThanThreshold
    name: DrupalLowCPU
    description: Scale-down if CPU <70% for 10 minutes
    threshold: 70
    policy: DrupalScaleDownPolicy
-   path: ag-app/app
    url: https://s3.amazonaws.com/s3-helix-ama/ui.tar.gz
drupal_databases: 
-   path: ag-app/app
    url: https://s3.amazonaws.com/s3-helix-ama/ui.tar.gz
-   db_type: default
    sql_url: https://s3.amazonaws.com/s3-helix-ama
    filename: testBruce124
    db_name: testBruce124
    drupal_db_name: solution_matrix
drupal_elb_health_check_target: testBruce124
drupal_elb_ssl_cert_name: drupal-elb-cert
drupal_instance_size: c4.8xlarge
drupal_lb_resource_name: DrupalNS
drupal_max_instances: 2
drupal_site_urls: testBruce124
drupal_sql_files: '[]'
mem_cache_instance_size: t2.micro
mysql_backup_retention: testBruce124
mysql_db_name: testBruce124
mysql_instance_size: c4.2xlarge
mysql_size_in_gb: testBruce124
mysql_user: testBruce124
