apache_asg_alarms: 
- !java.util.LinkedHashMap
   metric: CPUUtilization
   comparison_operator: GreaterThanThreshold
   description: Scale-up if CPU > 90% for 10 minutes
   threshold: 90
   policy: ApacheScaleUpPolicy
-  metric: CPUUtilization
   comparison_operator: LessThanThreshold
   description: Scale-down if CPU <70% for 10 minutes
   threshold: 30
   policy: ApacheScaleDownPolicy
apache_asg_grace_period: aa
apache_elb_health_check_target: bb
apache_elb_ssl_cert_name: cc
apache_instance_size: t2.medium
apache_lb_resource_name: dd
apache_max_instances: 5
apache_min_instances: 4
apache_multi_az: true
apache_vhosts: 
- !java.util.LinkedHashMap
   metric: CPUUtilization
   comparison_operator: LessThanThreshold
   description: Scale-down if CPU <70% for 10 minutes
   threshold: 30
   policy: ApacheScaleDownPolicy
-  documentroot: ff
   metric: CPUUtilization
   servername: ee
   comparison_operator: GreaterThanThreshold
   name: ' '
   description: Scale-up if CPU > 90% for 10 minutes
   threshold: 70
   shib_locationmatch: gg
   policy: JBossScaleUpPolicy
shib_X509Certificate: ii
shib_atrrib: kk
shib_entityid: hh
shib_service_location: jj
shib_spcert: mm
shib_spkey: ll
use_shibboleth: true
cust_urls: nn
jboss_asg_alarms: 
- !java.util.LinkedHashMap
   documentroot: ff
   metric: CPUUtilization
   servername: ee
   comparison_operator: GreaterThanThreshold
   name: ' '
   description: Scale-up if CPU > 90% for 10 minutes
   threshold: 70
   shib_locationmatch: gg
   policy: JBossScaleUpPolicy
-  metric: CPUUtilization
   comparison_operator: LessThanThreshold
   name: ' '
   description: Scale-down if CPU <70% for 10 minutes
   threshold: 60
   policy: JBossScaleDownPolicy
jboss_asg_grace_period: pp
jboss_default_log_level: vv
jboss_elb_health_check_target: qq
jboss_elb_ssl_cert_name: rr
jboss_instance_size: c4.8xlarge
jboss_lb_resource_name: ss
jboss_max_instances: 4
jboss_max_log_index: uu
jboss_max_log_size: tt
jboss_min_instances: 9
jboss_multi_az: true
jboss_target_path: oo
mongo_instance_size: c4.4xlarge
mongod_port: ww
