apache_asg_alarms: 
-  apache_high_cpu: 80
   apache_low_cpu: 40
apache_asg_grace_period: aa
apache_elb_health_check_target: bb
apache_elb_ssl_cert_name: cc
apache_instance_size: m4.xlarge
apache_lb_resource_name: dd
apache_max_instances: 5
apache_min_instances: 5
apache_multi_az: true
apache_vhosts: 
-  jboss_high_cpu: gg
shib_X509Certificate: ii
shib_atrrib: kk
shib_entityid: hh
shib_service_location: jj
shib_spcert: mm
shib_spkey: ll
use_shibboleth: true
cust_urls: nn
jboss_asg_alarms: 
-  jboss_high_cpu: 80
   jboss_low_cpu: 50
jboss_asg_grace_period: rr
jboss_default_log_level: xx
jboss_elb_health_check_target: ss
jboss_elb_ssl_cert_name: tt
jboss_instance_size: t2.micro
jboss_lb_resource_name: uu
jboss_max_instances: 3
jboss_max_log_index: ww
jboss_max_log_size: vv
jboss_min_instances: 3
jboss_target_path: oo
mongo_instance_size: c4.8xlarge
mongod_port: yy
